### ISSUE TITLE
Undefined variable 'horizontal_name' (and 'vertical_name')

### ISSUE THREAD

**Issue by ymbahe** [JBorrow/xl-pipeline#13]
https://github.com/JBorrow/xl-pipeline/blob/e21abd8dcd5a3c553fea7cbd91f7e46128f5b019/useful_extras/create_comparison.py#L114

This is using two undefined variables here, 'horizontal_name' and 'vertical_name'. It's not immediately obvious to me where these would come from, presumably one of the attributes of plot?

**Comment by JBorrow** [comment]
Ah yes - I must have forgotten to push that change - those name=X fields should be empty. I will push a fix.

**Comment by JBorrow** [comment]
The version of `velociraptor` on COSMA has been updated now,  by the way. To get the strings for the horizontal/vertical axes you'll need to run `velociraptor-plot`.
